filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
set_display_intro_string ("Good Afternoon Person with no name, Welcome to Coot version 0.9.8.3")
use_graphics_interface_state ()
set_filter_fileselection_filenames (0)
unset_sticky_sort_by_date ()
set_colour_map_rotation_on_read_pdb (21.00)
set_colour_map_rotation_on_read_pdb_c_only_flag (1)
set_density_size (16.00)
set_swap_difference_map_colours (0)
set_colour_map_rotation_for_map (14.00)
set_active_map_drag_flag (1)
set_idle_function_rotate_angle (1.00)
filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
set_display_intro_string ("Good afternoon . Welcome to Coot 0.9.8.3")
set_display_lists_for_maps (1)
set_filter_fileselection_filenames (0)
unset_sticky_sort_by_date ()
set_colour_map_rotation_on_read_pdb (21.00)
set_colour_map_rotation_on_read_pdb_c_only_flag (1)
set_density_size (16.00)
set_swap_difference_map_colours (0)
set_colour_map_rotation_for_map (14.00)
set_active_map_drag_flag (1)
set_idle_function_rotate_angle (1.00)
filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
;; # DIRECT SCHEME ((get-pdb-redo "3mwb"))
handle_read_draw_molecule_with_recentre ("3mwb_final.pdb", 1)
make_and_draw_map ("3mwb_final.mtz", "FWT", "PHWT", "", 0, 0)
make_and_draw_map ("3mwb_final.mtz", "DELFWT", "PHDELWT", "", 0, 1)
