(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-display-intro-string "Good Afternoon Person with no name, Welcome to Coot version 0.9.8.3")
(use-graphics-interface-state)
(set-filter-fileselection-filenames 0)
(unset-sticky-sort-by-date)
(set-colour-map-rotation-on-read-pdb 21.00)
(set-colour-map-rotation-on-read-pdb-c-only-flag 1)
(set-density-size 5.00)
(set-swap-difference-map-colours 0)
(set-colour-map-rotation-for-map 14.00)
(set-active-map-drag-flag 1)
(set-idle-function-rotate-angle 1.00)
(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-display-intro-string "Good afternoon . Welcome to Coot 0.9.8.3")
(set-display-lists-for-maps 1)
(set-filter-fileselection-filenames 0)
(unset-sticky-sort-by-date)
(set-colour-map-rotation-on-read-pdb 21.00)
(set-colour-map-rotation-on-read-pdb-c-only-flag 1)
(set-density-size 5.00)
(set-swap-difference-map-colours 0)
(set-colour-map-rotation-for-map 14.00)
(set-active-map-drag-flag 1)
(set-idle-function-rotate-angle 1.00)
(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(set-find-hydrogen-torsion 1)
(use-graphics-interface-state)
(handle-read-draw-molecule-with-recentre "/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine.pdb" 1)
(set-molecule-bonds-colour-map-rotation 0 140.00)
(set-colour-map-rotation-for-map 0.00)
(make-and-draw-map "/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map 0.00)
(close-molecule 1)
(close-molecule 2)
(set-colour-map-rotation-for-map 0.00)
(make-and-draw-map "/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map 0.00)
(close-molecule 3)
(close-molecule 4)
(set-colour-map-rotation-for-map 0.00)
(make-and-draw-map "/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map 0.00)
(close-molecule 5)
(close-molecule 6)
(set-colour-map-rotation-for-map 0.00)
(make-and-draw-map "/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map 0.00)
(close-molecule 7)
(close-molecule 8)
(set-colour-map-rotation-for-map 0.00)
(make-and-draw-map "/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map 0.00)
(close-molecule 9)
(close-molecule 10)
(set-colour-map-rotation-for-map 0.00)
(make-and-draw-map "/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map 0.00)
(close-molecule 11)
(close-molecule 12)
(set-colour-map-rotation-for-map 0.00)
(make-and-draw-map "/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map 0.00)
(close-molecule 13)
(close-molecule 14)
(set-colour-map-rotation-for-map 0.00)
(make-and-draw-map "/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map 0.00)
(close-molecule 15)
(close-molecule 16)
(set-colour-map-rotation-for-map 0.00)
(make-and-draw-map "/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map 0.00)
(close-molecule 17)
(close-molecule 18)
(set-colour-map-rotation-for-map 0.00)
(make-and-draw-map "/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map 0.00)
(close-molecule 19)
(close-molecule 20)
(set-colour-map-rotation-for-map 0.00)
(make-and-draw-map "/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map 0.00)
(close-molecule 21)
(close-molecule 22)
(set-colour-map-rotation-for-map 0.00)
(make-and-draw-map "/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map 0.00)
(close-molecule 23)
(close-molecule 24)
(set-colour-map-rotation-for-map 0.00)
(make-and-draw-map "/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map 0.00)
(close-molecule 25)
(close-molecule 26)
(set-colour-map-rotation-for-map 0.00)
(make-and-draw-map "/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map 0.00)
(close-molecule 27)
(close-molecule 28)
(set-colour-map-rotation-for-map 0.00)
(make-and-draw-map "/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map 0.00)
(close-molecule 29)
(close-molecule 30)
(set-colour-map-rotation-for-map 0.00)
(make-and-draw-map "/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map 0.00)
(close-molecule 31)
(close-molecule 32)
(set-colour-map-rotation-for-map 0.00)
(make-and-draw-map "/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map 0.00)
(close-molecule 33)
(close-molecule 34)
(set-colour-map-rotation-for-map 0.00)
(make-and-draw-map "/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map 0.00)
(close-molecule 35)
(close-molecule 36)
(set-colour-map-rotation-for-map 0.00)
(make-and-draw-map "/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map 0.00)
(close-molecule 37)
(close-molecule 38)
(set-colour-map-rotation-for-map 0.00)
(make-and-draw-map "/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map 0.00)
(close-molecule 39)
(close-molecule 40)
(set-colour-map-rotation-for-map 0.00)
(make-and-draw-map "/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map 0.00)
(close-molecule 41)
(close-molecule 42)
(set-colour-map-rotation-for-map 0.00)
(make-and-draw-map "/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map 0.00)
(close-molecule 43)
(close-molecule 44)
(set-colour-map-rotation-for-map 0.00)
(make-and-draw-map "/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map 0.00)
(close-molecule 45)
(close-molecule 46)
(set-colour-map-rotation-for-map 0.00)
(make-and-draw-map "/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map 0.00)
(close-molecule 47)
(close-molecule 48)
(set-colour-map-rotation-for-map 0.00)
(make-and-draw-map "/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map 0.00)
(close-molecule 49)
(close-molecule 50)
(set-colour-map-rotation-for-map 0.00)
(make-and-draw-map "/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map 0.00)
(close-molecule 51)
(close-molecule 52)
(set-colour-map-rotation-for-map 0.00)
(make-and-draw-map "/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map 0.00)
(close-molecule 53)
(close-molecule 54)
(set-colour-map-rotation-for-map 0.00)
(make-and-draw-map "/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map 0.00)
(close-molecule 55)
(close-molecule 56)
(set-colour-map-rotation-for-map 0.00)
(make-and-draw-map "/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map 0.00)
(close-molecule 57)
(close-molecule 58)
(set-colour-map-rotation-for-map 0.00)
(make-and-draw-map "/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map 0.00)
(close-molecule 0)
(close-molecule 59)
(close-molecule 60)
(handle-read-draw-molecule-with-recentre "/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/3mwbSimu-Ann-10Steps_refine_1.pdb" 1)
(set-molecule-bonds-colour-map-rotation 61 30.00)
(set-colour-map-rotation-for-map 0.00)
(make-and-draw-map "/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/3mwbSimu-Ann-10Steps_refine_1.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/3mwbSimu-Ann-10Steps_refine_1.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(set-colour-map-rotation-for-map 0.00)
