(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-display-intro-string "Good Afternoon Person with no name, Welcome to Coot version 0.9.8.3")
(use-graphics-interface-state)
(set-filter-fileselection-filenames 0)
(unset-sticky-sort-by-date)
(set-colour-map-rotation-on-read-pdb 21.00)
(set-colour-map-rotation-on-read-pdb-c-only-flag 1)
(set-density-size 5.00)
(set-swap-difference-map-colours 0)
(set-colour-map-rotation-for-map 14.00)
(set-active-map-drag-flag 1)
(set-idle-function-rotate-angle 1.00)
(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-display-intro-string "Good afternoon . Welcome to Coot 0.9.8.3")
(set-display-lists-for-maps 1)
(set-filter-fileselection-filenames 0)
(unset-sticky-sort-by-date)
(set-colour-map-rotation-on-read-pdb 21.00)
(set-colour-map-rotation-on-read-pdb-c-only-flag 1)
(set-density-size 5.00)
(set-swap-difference-map-colours 0)
(set-colour-map-rotation-for-map 14.00)
(set-active-map-drag-flag 1)
(set-idle-function-rotate-angle 1.00)
(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(handle-read-draw-molecule-with-recentre "Refine_2/6t3x_Step0_plain_refine_2.pdb" 1)
(use-graphics-interface-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(make-and-draw-map-with-reso-with-refmac-params "/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/6t3x/Manual-Refine/Step0_plain_Simu_ann/Refine_2/6t3x_Step0_plain_refine_2.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0 0 "Fobs:None-specified" "SigF:None-specified" "RFree:None-specified" 0 0 0 0.00 0.00)
(make-and-draw-map-with-reso-with-refmac-params "/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/6t3x/Manual-Refine/Step0_plain_Simu_ann/Refine_2/6t3x_Step0_plain_refine_2.mtz" "FOFCWT" "PHFOFCWT" "" 0 1 0 "Fobs:None-specified" "SigF:None-specified" "RFree:None-specified" 0 0 0 0.00 0.00)
