filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
set_display_intro_string ("Good Afternoon Person with no name, Welcome to Coot version 0.9.8.3")
use_graphics_interface_state ()
set_filter_fileselection_filenames (0)
unset_sticky_sort_by_date ()
set_colour_map_rotation_on_read_pdb (21.00)
set_colour_map_rotation_on_read_pdb_c_only_flag (1)
set_density_size (5.00)
set_swap_difference_map_colours (0)
set_colour_map_rotation_for_map (14.00)
set_active_map_drag_flag (1)
set_idle_function_rotate_angle (1.00)
filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
set_display_intro_string ("Good afternoon . Welcome to Coot 0.9.8.3")
set_display_lists_for_maps (1)
set_filter_fileselection_filenames (0)
unset_sticky_sort_by_date ()
set_colour_map_rotation_on_read_pdb (21.00)
set_colour_map_rotation_on_read_pdb_c_only_flag (1)
set_density_size (5.00)
set_swap_difference_map_colours (0)
set_colour_map_rotation_for_map (14.00)
set_active_map_drag_flag (1)
set_idle_function_rotate_angle (1.00)
filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
set_find_hydrogen_torsion (1)
use_graphics_interface_state ()
handle_read_draw_molecule_with_recentre ("/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine.pdb", 1)
set_molecule_bonds_colour_map_rotation (0, 140.00)
set_colour_map_rotation_for_map (0.00)
make_and_draw_map ("/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map (0.00)
close_molecule (1)
close_molecule (2)
set_colour_map_rotation_for_map (0.00)
make_and_draw_map ("/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map (0.00)
close_molecule (3)
close_molecule (4)
set_colour_map_rotation_for_map (0.00)
make_and_draw_map ("/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map (0.00)
close_molecule (5)
close_molecule (6)
set_colour_map_rotation_for_map (0.00)
make_and_draw_map ("/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map (0.00)
close_molecule (7)
close_molecule (8)
set_colour_map_rotation_for_map (0.00)
make_and_draw_map ("/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map (0.00)
close_molecule (9)
close_molecule (10)
set_colour_map_rotation_for_map (0.00)
make_and_draw_map ("/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map (0.00)
close_molecule (11)
close_molecule (12)
set_colour_map_rotation_for_map (0.00)
make_and_draw_map ("/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map (0.00)
close_molecule (13)
close_molecule (14)
set_colour_map_rotation_for_map (0.00)
make_and_draw_map ("/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map (0.00)
close_molecule (15)
close_molecule (16)
set_colour_map_rotation_for_map (0.00)
make_and_draw_map ("/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map (0.00)
close_molecule (17)
close_molecule (18)
set_colour_map_rotation_for_map (0.00)
make_and_draw_map ("/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map (0.00)
close_molecule (19)
close_molecule (20)
set_colour_map_rotation_for_map (0.00)
make_and_draw_map ("/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map (0.00)
close_molecule (21)
close_molecule (22)
set_colour_map_rotation_for_map (0.00)
make_and_draw_map ("/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map (0.00)
close_molecule (23)
close_molecule (24)
set_colour_map_rotation_for_map (0.00)
make_and_draw_map ("/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map (0.00)
close_molecule (25)
close_molecule (26)
set_colour_map_rotation_for_map (0.00)
make_and_draw_map ("/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map (0.00)
close_molecule (27)
close_molecule (28)
set_colour_map_rotation_for_map (0.00)
make_and_draw_map ("/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map (0.00)
close_molecule (29)
close_molecule (30)
set_colour_map_rotation_for_map (0.00)
make_and_draw_map ("/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map (0.00)
close_molecule (31)
close_molecule (32)
set_colour_map_rotation_for_map (0.00)
make_and_draw_map ("/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map (0.00)
close_molecule (33)
close_molecule (34)
set_colour_map_rotation_for_map (0.00)
make_and_draw_map ("/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map (0.00)
close_molecule (35)
close_molecule (36)
set_colour_map_rotation_for_map (0.00)
make_and_draw_map ("/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map (0.00)
close_molecule (37)
close_molecule (38)
set_colour_map_rotation_for_map (0.00)
make_and_draw_map ("/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map (0.00)
close_molecule (39)
close_molecule (40)
set_colour_map_rotation_for_map (0.00)
make_and_draw_map ("/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map (0.00)
close_molecule (41)
close_molecule (42)
set_colour_map_rotation_for_map (0.00)
make_and_draw_map ("/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map (0.00)
close_molecule (43)
close_molecule (44)
set_colour_map_rotation_for_map (0.00)
make_and_draw_map ("/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map (0.00)
close_molecule (45)
close_molecule (46)
set_colour_map_rotation_for_map (0.00)
make_and_draw_map ("/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map (0.00)
close_molecule (47)
close_molecule (48)
set_colour_map_rotation_for_map (0.00)
make_and_draw_map ("/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map (0.00)
close_molecule (49)
close_molecule (50)
set_colour_map_rotation_for_map (0.00)
make_and_draw_map ("/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map (0.00)
close_molecule (51)
close_molecule (52)
set_colour_map_rotation_for_map (0.00)
make_and_draw_map ("/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map (0.00)
close_molecule (53)
close_molecule (54)
set_colour_map_rotation_for_map (0.00)
make_and_draw_map ("/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map (0.00)
close_molecule (55)
close_molecule (56)
set_colour_map_rotation_for_map (0.00)
make_and_draw_map ("/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map (0.00)
close_molecule (57)
close_molecule (58)
set_colour_map_rotation_for_map (0.00)
make_and_draw_map ("/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/.comm/tmp.refine_maps.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map (0.00)
close_molecule (0)
close_molecule (59)
close_molecule (60)
handle_read_draw_molecule_with_recentre ("/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/3mwbSimu-Ann-10Steps_refine_1.pdb", 1)
set_molecule_bonds_colour_map_rotation (61, 30.00)
set_colour_map_rotation_for_map (0.00)
make_and_draw_map ("/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/3mwbSimu-Ann-10Steps_refine_1.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("/home_val/sbazzi/Beyond_lys_cys/Backbone/Revise1_Comm_Chem/Refinemnt/3mwb/Manual-refinemt/Step0_plain_refin_Simu-Ann-10Steps/Refine_1/3mwbSimu-Ann-10Steps_refine_1.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
set_colour_map_rotation_for_map (0.00)
